// Code generated by protoc-gen-go. DO NOT EDIT.
// source: desc_test_proto3.proto

package testprotos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import jhump_protoreflect_desc "github.com/prasek/protoer/internal/test/golang/testprotos/pkg"
import google_protobuf1 "github.com/golang/protobuf/protoc-gen-go/descriptor"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Proto3Enum int32

const (
	Proto3Enum_UNKNOWN Proto3Enum = 0
	Proto3Enum_VALUE1  Proto3Enum = 1
	Proto3Enum_VALUE2  Proto3Enum = 2
)

var Proto3Enum_name = map[int32]string{
	0: "UNKNOWN",
	1: "VALUE1",
	2: "VALUE2",
}
var Proto3Enum_value = map[string]int32{
	"UNKNOWN": 0,
	"VALUE1":  1,
	"VALUE2":  2,
}

func (x Proto3Enum) String() string {
	return proto.EnumName(Proto3Enum_name, int32(x))
}
func (Proto3Enum) EnumDescriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

type TestRequest struct {
	Foo   []Proto3Enum                                    `protobuf:"varint,1,rep,packed,name=foo,enum=testprotos.Proto3Enum" json:"foo,omitempty"`
	Bar   string                                          `protobuf:"bytes,2,opt,name=bar" json:"bar,omitempty"`
	Baz   *TestMessage                                    `protobuf:"bytes,3,opt,name=baz" json:"baz,omitempty"`
	Snafu *TestMessage_NestedMessage_AnotherNestedMessage `protobuf:"bytes,4,opt,name=snafu" json:"snafu,omitempty"`
	Flags map[string]bool                                 `protobuf:"bytes,5,rep,name=flags" json:"flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *TestRequest) Reset()                    { *m = TestRequest{} }
func (m *TestRequest) String() string            { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()               {}
func (*TestRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *TestRequest) GetFoo() []Proto3Enum {
	if m != nil {
		return m.Foo
	}
	return nil
}

func (m *TestRequest) GetBar() string {
	if m != nil {
		return m.Bar
	}
	return ""
}

func (m *TestRequest) GetBaz() *TestMessage {
	if m != nil {
		return m.Baz
	}
	return nil
}

func (m *TestRequest) GetSnafu() *TestMessage_NestedMessage_AnotherNestedMessage {
	if m != nil {
		return m.Snafu
	}
	return nil
}

func (m *TestRequest) GetFlags() map[string]bool {
	if m != nil {
		return m.Flags
	}
	return nil
}

type TestResponse struct {
	Atm *AnotherTestMessage `protobuf:"bytes,1,opt,name=atm" json:"atm,omitempty"`
	Vs  []int32             `protobuf:"varint,2,rep,packed,name=vs" json:"vs,omitempty"`
}

func (m *TestResponse) Reset()                    { *m = TestResponse{} }
func (m *TestResponse) String() string            { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()               {}
func (*TestResponse) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *TestResponse) GetAtm() *AnotherTestMessage {
	if m != nil {
		return m.Atm
	}
	return nil
}

func (m *TestResponse) GetVs() []int32 {
	if m != nil {
		return m.Vs
	}
	return nil
}

type CustomOption struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value int32  `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
}

func (m *CustomOption) Reset()                    { *m = CustomOption{} }
func (m *CustomOption) String() string            { return proto.CompactTextString(m) }
func (*CustomOption) ProtoMessage()               {}
func (*CustomOption) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{2} }

func (m *CustomOption) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomOption) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

var E_Custom = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.MethodOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50059,
	Name:          "testprotos.custom",
	Tag:           "varint,50059,opt,name=custom",
	Filename:      "desc_test_proto3.proto",
}

var E_Custom2 = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.MethodOptions)(nil),
	ExtensionType: (*CustomOption)(nil),
	Field:         50060,
	Name:          "testprotos.custom2",
	Tag:           "bytes,50060,opt,name=custom2",
	Filename:      "desc_test_proto3.proto",
}

func init() {
	proto.RegisterType((*TestRequest)(nil), "testprotos.TestRequest")
	proto.RegisterType((*TestResponse)(nil), "testprotos.TestResponse")
	proto.RegisterType((*CustomOption)(nil), "testprotos.CustomOption")
	proto.RegisterEnum("testprotos.Proto3Enum", Proto3Enum_name, Proto3Enum_value)
	proto.RegisterExtension(E_Custom)
	proto.RegisterExtension(E_Custom2)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TestService service

type TestServiceClient interface {
	DoSomething(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*jhump_protoreflect_desc.Bar, error)
	DoSomethingElse(ctx context.Context, opts ...grpc.CallOption) (TestService_DoSomethingElseClient, error)
	DoSomethingAgain(ctx context.Context, in *jhump_protoreflect_desc.Bar, opts ...grpc.CallOption) (TestService_DoSomethingAgainClient, error)
	DoSomethingForever(ctx context.Context, opts ...grpc.CallOption) (TestService_DoSomethingForeverClient, error)
}

type testServiceClient struct {
	cc *grpc.ClientConn
}

func NewTestServiceClient(cc *grpc.ClientConn) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) DoSomething(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*jhump_protoreflect_desc.Bar, error) {
	out := new(jhump_protoreflect_desc.Bar)
	err := grpc.Invoke(ctx, "/testprotos.TestService/DoSomething", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) DoSomethingElse(ctx context.Context, opts ...grpc.CallOption) (TestService_DoSomethingElseClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TestService_serviceDesc.Streams[0], c.cc, "/testprotos.TestService/DoSomethingElse", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceDoSomethingElseClient{stream}
	return x, nil
}

type TestService_DoSomethingElseClient interface {
	Send(*TestMessage) error
	CloseAndRecv() (*TestResponse, error)
	grpc.ClientStream
}

type testServiceDoSomethingElseClient struct {
	grpc.ClientStream
}

func (x *testServiceDoSomethingElseClient) Send(m *TestMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *testServiceDoSomethingElseClient) CloseAndRecv() (*TestResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(TestResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *testServiceClient) DoSomethingAgain(ctx context.Context, in *jhump_protoreflect_desc.Bar, opts ...grpc.CallOption) (TestService_DoSomethingAgainClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TestService_serviceDesc.Streams[1], c.cc, "/testprotos.TestService/DoSomethingAgain", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceDoSomethingAgainClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TestService_DoSomethingAgainClient interface {
	Recv() (*AnotherTestMessage, error)
	grpc.ClientStream
}

type testServiceDoSomethingAgainClient struct {
	grpc.ClientStream
}

func (x *testServiceDoSomethingAgainClient) Recv() (*AnotherTestMessage, error) {
	m := new(AnotherTestMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *testServiceClient) DoSomethingForever(ctx context.Context, opts ...grpc.CallOption) (TestService_DoSomethingForeverClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TestService_serviceDesc.Streams[2], c.cc, "/testprotos.TestService/DoSomethingForever", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceDoSomethingForeverClient{stream}
	return x, nil
}

type TestService_DoSomethingForeverClient interface {
	Send(*TestRequest) error
	Recv() (*TestResponse, error)
	grpc.ClientStream
}

type testServiceDoSomethingForeverClient struct {
	grpc.ClientStream
}

func (x *testServiceDoSomethingForeverClient) Send(m *TestRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *testServiceDoSomethingForeverClient) Recv() (*TestResponse, error) {
	m := new(TestResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for TestService service

type TestServiceServer interface {
	DoSomething(context.Context, *TestRequest) (*jhump_protoreflect_desc.Bar, error)
	DoSomethingElse(TestService_DoSomethingElseServer) error
	DoSomethingAgain(*jhump_protoreflect_desc.Bar, TestService_DoSomethingAgainServer) error
	DoSomethingForever(TestService_DoSomethingForeverServer) error
}

func RegisterTestServiceServer(s *grpc.Server, srv TestServiceServer) {
	s.RegisterService(&_TestService_serviceDesc, srv)
}

func _TestService_DoSomething_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).DoSomething(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testprotos.TestService/DoSomething",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).DoSomething(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_DoSomethingElse_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).DoSomethingElse(&testServiceDoSomethingElseServer{stream})
}

type TestService_DoSomethingElseServer interface {
	SendAndClose(*TestResponse) error
	Recv() (*TestMessage, error)
	grpc.ServerStream
}

type testServiceDoSomethingElseServer struct {
	grpc.ServerStream
}

func (x *testServiceDoSomethingElseServer) SendAndClose(m *TestResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *testServiceDoSomethingElseServer) Recv() (*TestMessage, error) {
	m := new(TestMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TestService_DoSomethingAgain_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(jhump_protoreflect_desc.Bar)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestServiceServer).DoSomethingAgain(m, &testServiceDoSomethingAgainServer{stream})
}

type TestService_DoSomethingAgainServer interface {
	Send(*AnotherTestMessage) error
	grpc.ServerStream
}

type testServiceDoSomethingAgainServer struct {
	grpc.ServerStream
}

func (x *testServiceDoSomethingAgainServer) Send(m *AnotherTestMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _TestService_DoSomethingForever_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).DoSomethingForever(&testServiceDoSomethingForeverServer{stream})
}

type TestService_DoSomethingForeverServer interface {
	Send(*TestResponse) error
	Recv() (*TestRequest, error)
	grpc.ServerStream
}

type testServiceDoSomethingForeverServer struct {
	grpc.ServerStream
}

func (x *testServiceDoSomethingForeverServer) Send(m *TestResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *testServiceDoSomethingForeverServer) Recv() (*TestRequest, error) {
	m := new(TestRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "testprotos.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoSomething",
			Handler:    _TestService_DoSomething_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DoSomethingElse",
			Handler:       _TestService_DoSomethingElse_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DoSomethingAgain",
			Handler:       _TestService_DoSomethingAgain_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DoSomethingForever",
			Handler:       _TestService_DoSomethingForever_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "desc_test_proto3.proto",
}

func init() { proto.RegisterFile("desc_test_proto3.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 603 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcd, 0x4e, 0xdb, 0x4c,
	0x14, 0xc5, 0x36, 0x81, 0xef, 0xbb, 0x46, 0xd4, 0x9a, 0x56, 0x60, 0x45, 0x15, 0x8a, 0xb2, 0x72,
	0xbb, 0xb0, 0xc1, 0x2c, 0x1a, 0x65, 0x07, 0x6d, 0xd8, 0x50, 0x02, 0x32, 0xd0, 0xbf, 0x0d, 0x72,
	0xc2, 0x8d, 0xe3, 0xc6, 0xf6, 0xb8, 0x33, 0xe3, 0x48, 0xf0, 0x02, 0x2c, 0xda, 0x07, 0x42, 0x7d,
	0x91, 0xb2, 0xee, 0x93, 0x54, 0x9e, 0x31, 0xc4, 0x69, 0x15, 0x58, 0xf9, 0xce, 0x9d, 0x73, 0xcf,
	0x9c, 0xfb, 0x67, 0xd8, 0xb8, 0x44, 0x3e, 0xbc, 0x10, 0xc8, 0xc5, 0x45, 0xce, 0xa8, 0xa0, 0xbb,
	0xae, 0xfc, 0x10, 0x28, 0x5d, 0xd2, 0xe4, 0x4d, 0xeb, 0x01, 0xb3, 0xa3, 0x6e, 0x9b, 0x9b, 0xf9,
	0x24, 0xf2, 0x6a, 0x91, 0x93, 0xa8, 0xba, 0x68, 0x45, 0x94, 0x46, 0x09, 0x7a, 0xf2, 0x34, 0x28,
	0x46, 0x12, 0xc4, 0xe2, 0x5c, 0x50, 0xa6, 0x10, 0xed, 0x9f, 0x3a, 0x98, 0x67, 0xc8, 0x45, 0x80,
	0xdf, 0x0a, 0xe4, 0x82, 0x38, 0x60, 0x8c, 0x28, 0xb5, 0xb5, 0x96, 0xe1, 0xac, 0xfb, 0x1b, 0xee,
	0xec, 0x59, 0xf7, 0x44, 0xea, 0xe9, 0x65, 0x45, 0x1a, 0x94, 0x10, 0x62, 0x81, 0x31, 0x08, 0x99,
	0xad, 0xb7, 0x34, 0xe7, 0xff, 0xa0, 0x34, 0xc9, 0xab, 0xd2, 0x73, 0x6d, 0x1b, 0x2d, 0xcd, 0x31,
	0xfd, 0xcd, 0x7a, 0x6c, 0xf9, 0xc2, 0x11, 0x72, 0x1e, 0x46, 0x58, 0x42, 0xaf, 0xc9, 0x09, 0x34,
	0x78, 0x16, 0x8e, 0x0a, 0x7b, 0x59, 0x82, 0xbb, 0x0b, 0xc0, 0x6e, 0x1f, 0xb9, 0xc0, 0xcb, 0xfb,
	0xd3, 0x5e, 0x46, 0xc5, 0x18, 0xd9, 0x9c, 0x33, 0x50, 0x44, 0xa4, 0x03, 0x8d, 0x51, 0x12, 0x46,
	0xdc, 0x6e, 0xb4, 0x0c, 0xc7, 0xf4, 0xdb, 0x7f, 0x33, 0x56, 0x09, 0xba, 0x07, 0x25, 0xa8, 0x97,
	0x09, 0x76, 0x15, 0xa8, 0x80, 0x66, 0x07, 0x60, 0xe6, 0x2c, 0xd3, 0x9a, 0xe0, 0x95, 0xad, 0xa9,
	0xb4, 0x26, 0x78, 0x45, 0x5e, 0x40, 0x63, 0x1a, 0x26, 0x05, 0xca, 0x54, 0xff, 0x0b, 0xd4, 0xa1,
	0xab, 0x77, 0xb4, 0xf6, 0x09, 0xac, 0x29, 0x6a, 0x9e, 0xd3, 0x8c, 0x23, 0xd9, 0x06, 0x23, 0x14,
	0xa9, 0x8c, 0x35, 0xfd, 0xad, 0xba, 0x82, 0x4a, 0xf9, 0x5c, 0x1d, 0x42, 0x91, 0x92, 0x75, 0xd0,
	0xa7, 0xdc, 0xd6, 0x5b, 0x86, 0xd3, 0x08, 0xf4, 0x29, 0x6f, 0x77, 0x60, 0xed, 0x6d, 0xc1, 0x05,
	0x4d, 0x8f, 0x73, 0x11, 0xd3, 0x8c, 0x10, 0x58, 0xce, 0xc2, 0x14, 0x2b, 0x39, 0xd2, 0x9e, 0xd7,
	0xd3, 0xa8, 0xf4, 0xbc, 0xde, 0x01, 0x98, 0x75, 0x88, 0x98, 0xb0, 0x7a, 0xde, 0x3f, 0xec, 0x1f,
	0x7f, 0xec, 0x5b, 0x4b, 0x04, 0x60, 0xe5, 0xc3, 0xde, 0xfb, 0xf3, 0xde, 0x8e, 0xa5, 0x3d, 0xd8,
	0xbe, 0xa5, 0xfb, 0xbf, 0xaa, 0xde, 0x9f, 0x22, 0x9b, 0xc6, 0x43, 0x24, 0x9f, 0xc1, 0x7c, 0x47,
	0x4f, 0x69, 0x8a, 0x62, 0x1c, 0x67, 0x11, 0xd9, 0x5c, 0x50, 0xc2, 0xe6, 0x4b, 0xf7, 0xeb, 0xb8,
	0x48, 0x73, 0x35, 0x41, 0x0c, 0x47, 0x09, 0x0e, 0x85, 0x5b, 0x4e, 0x96, 0xbb, 0x1f, 0xb2, 0xf6,
	0xf3, 0xbb, 0x5b, 0x5b, 0xfb, 0x7d, 0x6b, 0x9b, 0xb0, 0x2a, 0x67, 0xd4, 0xdf, 0xb5, 0xde, 0x90,
	0x03, 0x78, 0x56, 0xa3, 0xee, 0x25, 0x1c, 0xc9, 0xa2, 0x01, 0x69, 0xda, 0xff, 0xbe, 0xab, 0xea,
	0xeb, 0x68, 0xe4, 0x13, 0x58, 0x35, 0x9e, 0xbd, 0x28, 0x8c, 0x33, 0xf2, 0xa8, 0x9c, 0xe6, 0x13,
	0x6d, 0x68, 0x2f, 0xdf, 0xdd, 0xda, 0x4b, 0xdb, 0x1a, 0x39, 0x04, 0x52, 0x63, 0x3e, 0xa0, 0x0c,
	0xa7, 0xc8, 0x16, 0xd7, 0xe0, 0x11, 0x91, 0xdb, 0x5a, 0xb7, 0x03, 0x2b, 0x43, 0xd9, 0x46, 0xb2,
	0xe5, 0xaa, 0x15, 0x74, 0xef, 0x57, 0xd0, 0x3d, 0x42, 0x31, 0xa6, 0x97, 0xaa, 0xbf, 0xdc, 0xfe,
	0x7e, 0x63, 0xc8, 0xa9, 0xaa, 0xf0, 0xdd, 0x33, 0x58, 0x55, 0x96, 0xff, 0x64, 0xe8, 0x8f, 0x1b,
	0xb5, 0x69, 0x73, 0x52, 0xea, 0xd3, 0x13, 0xdc, 0x53, 0xed, 0x77, 0xbf, 0x74, 0xa2, 0x58, 0x8c,
	0x8b, 0x81, 0x3b, 0xa4, 0xa9, 0x27, 0xcb, 0xe5, 0xd5, 0xcb, 0xe5, 0xc5, 0x99, 0x40, 0x96, 0x85,
	0x89, 0x17, 0xd1, 0x24, 0xcc, 0x22, 0x6f, 0xc6, 0x38, 0x58, 0x51, 0x3f, 0xa2, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xbd, 0xd8, 0xf6, 0x40, 0x9b, 0x04, 0x00, 0x00,
}
