// Code generated by protoc-gen-go. DO NOT EDIT.
// source: desc_test_options.proto

package testprotos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ReallySimpleEnum int32

const (
	ReallySimpleEnum_VALUE ReallySimpleEnum = 1
)

var ReallySimpleEnum_name = map[int32]string{
	1: "VALUE",
}
var ReallySimpleEnum_value = map[string]int32{
	"VALUE": 1,
}

func (x ReallySimpleEnum) Enum() *ReallySimpleEnum {
	p := new(ReallySimpleEnum)
	*p = x
	return p
}
func (x ReallySimpleEnum) String() string {
	return proto.EnumName(ReallySimpleEnum_name, int32(x))
}
func (x *ReallySimpleEnum) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReallySimpleEnum_value, data, "ReallySimpleEnum")
	if err != nil {
		return err
	}
	*x = ReallySimpleEnum(value)
	return nil
}
func (ReallySimpleEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

type ReallySimpleMessage struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReallySimpleMessage) Reset()                    { *m = ReallySimpleMessage{} }
func (m *ReallySimpleMessage) String() string            { return proto.CompactTextString(m) }
func (*ReallySimpleMessage) ProtoMessage()               {}
func (*ReallySimpleMessage) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *ReallySimpleMessage) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ReallySimpleMessage) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

var E_Mfubar = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         10101,
	Name:          "testprotos.mfubar",
	Tag:           "varint,10101,opt,name=mfubar",
	Filename:      "desc_test_options.proto",
}

var E_Ffubar = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.FieldOptions)(nil),
	ExtensionType: ([]string)(nil),
	Field:         10101,
	Name:          "testprotos.ffubar",
	Tag:           "bytes,10101,rep,name=ffubar",
	Filename:      "desc_test_options.proto",
}

var E_Ffubarb = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.FieldOptions)(nil),
	ExtensionType: ([]byte)(nil),
	Field:         10102,
	Name:          "testprotos.ffubarb",
	Tag:           "bytes,10102,opt,name=ffubarb",
	Filename:      "desc_test_options.proto",
}

var E_Efubar = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         10101,
	Name:          "testprotos.efubar",
	Tag:           "varint,10101,opt,name=efubar",
	Filename:      "desc_test_options.proto",
}

var E_Efubars = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         10102,
	Name:          "testprotos.efubars",
	Tag:           "zigzag32,10102,opt,name=efubars",
	Filename:      "desc_test_options.proto",
}

var E_Efubarsf = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         10103,
	Name:          "testprotos.efubarsf",
	Tag:           "fixed32,10103,opt,name=efubarsf",
	Filename:      "desc_test_options.proto",
}

var E_Efubaru = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumOptions)(nil),
	ExtensionType: (*uint32)(nil),
	Field:         10104,
	Name:          "testprotos.efubaru",
	Tag:           "varint,10104,opt,name=efubaru",
	Filename:      "desc_test_options.proto",
}

var E_Efubaruf = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumOptions)(nil),
	ExtensionType: (*uint32)(nil),
	Field:         10105,
	Name:          "testprotos.efubaruf",
	Tag:           "fixed32,10105,opt,name=efubaruf",
	Filename:      "desc_test_options.proto",
}

var E_Evfubar = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumValueOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         10101,
	Name:          "testprotos.evfubar",
	Tag:           "varint,10101,opt,name=evfubar",
	Filename:      "desc_test_options.proto",
}

var E_Evfubars = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumValueOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         10102,
	Name:          "testprotos.evfubars",
	Tag:           "zigzag64,10102,opt,name=evfubars",
	Filename:      "desc_test_options.proto",
}

var E_Evfubarsf = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumValueOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         10103,
	Name:          "testprotos.evfubarsf",
	Tag:           "fixed64,10103,opt,name=evfubarsf",
	Filename:      "desc_test_options.proto",
}

var E_Evfubaru = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumValueOptions)(nil),
	ExtensionType: (*uint64)(nil),
	Field:         10104,
	Name:          "testprotos.evfubaru",
	Tag:           "varint,10104,opt,name=evfubaru",
	Filename:      "desc_test_options.proto",
}

var E_Evfubaruf = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumValueOptions)(nil),
	ExtensionType: (*uint64)(nil),
	Field:         10105,
	Name:          "testprotos.evfubaruf",
	Tag:           "fixed64,10105,opt,name=evfubaruf",
	Filename:      "desc_test_options.proto",
}

var E_Sfubar = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.ServiceOptions)(nil),
	ExtensionType: (*ReallySimpleMessage)(nil),
	Field:         10101,
	Name:          "testprotos.sfubar",
	Tag:           "bytes,10101,opt,name=sfubar",
	Filename:      "desc_test_options.proto",
}

var E_Sfubare = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.ServiceOptions)(nil),
	ExtensionType: (*ReallySimpleEnum)(nil),
	Field:         10102,
	Name:          "testprotos.sfubare",
	Tag:           "varint,10102,opt,name=sfubare,enum=testprotos.ReallySimpleEnum",
	Filename:      "desc_test_options.proto",
}

var E_Mtfubar = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.MethodOptions)(nil),
	ExtensionType: ([]float32)(nil),
	Field:         10101,
	Name:          "testprotos.mtfubar",
	Tag:           "fixed32,10101,rep,name=mtfubar",
	Filename:      "desc_test_options.proto",
}

var E_Mtfubard = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.MethodOptions)(nil),
	ExtensionType: (*float64)(nil),
	Field:         10102,
	Name:          "testprotos.mtfubard",
	Tag:           "fixed64,10102,opt,name=mtfubard",
	Filename:      "desc_test_options.proto",
}

var E_Exfubar = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.ExtensionRangeOptions)(nil),
	ExtensionType: ([]string)(nil),
	Field:         10101,
	Name:          "testprotos.exfubar",
	Tag:           "bytes,10101,rep,name=exfubar",
	Filename:      "desc_test_options.proto",
}

var E_Exfubarb = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.ExtensionRangeOptions)(nil),
	ExtensionType: ([]byte)(nil),
	Field:         10102,
	Name:          "testprotos.exfubarb",
	Tag:           "bytes,10102,opt,name=exfubarb",
	Filename:      "desc_test_options.proto",
}

func init() {
	proto.RegisterType((*ReallySimpleMessage)(nil), "testprotos.ReallySimpleMessage")
	proto.RegisterEnum("testprotos.ReallySimpleEnum", ReallySimpleEnum_name, ReallySimpleEnum_value)
	proto.RegisterExtension(E_Mfubar)
	proto.RegisterExtension(E_Ffubar)
	proto.RegisterExtension(E_Ffubarb)
	proto.RegisterExtension(E_Efubar)
	proto.RegisterExtension(E_Efubars)
	proto.RegisterExtension(E_Efubarsf)
	proto.RegisterExtension(E_Efubaru)
	proto.RegisterExtension(E_Efubaruf)
	proto.RegisterExtension(E_Evfubar)
	proto.RegisterExtension(E_Evfubars)
	proto.RegisterExtension(E_Evfubarsf)
	proto.RegisterExtension(E_Evfubaru)
	proto.RegisterExtension(E_Evfubaruf)
	proto.RegisterExtension(E_Sfubar)
	proto.RegisterExtension(E_Sfubare)
	proto.RegisterExtension(E_Mtfubar)
	proto.RegisterExtension(E_Mtfubard)
	proto.RegisterExtension(E_Exfubar)
	proto.RegisterExtension(E_Exfubarb)
}

func init() { proto.RegisterFile("desc_test_options.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 526 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcb, 0x6f, 0xd3, 0x4c,
	0x14, 0xc5, 0xe5, 0x34, 0x8d, 0x93, 0xfb, 0x7d, 0x94, 0x60, 0x16, 0x44, 0xa8, 0xa5, 0x81, 0x05,
	0x8a, 0x58, 0xd8, 0x52, 0x25, 0x20, 0x19, 0x10, 0xa2, 0xa0, 0xb2, 0xe2, 0x21, 0x4d, 0x45, 0x05,
	0x6c, 0x2a, 0x27, 0x1e, 0x3b, 0x83, 0x6c, 0x8f, 0xe5, 0x99, 0xa9, 0xca, 0x1f, 0xce, 0x6b, 0x87,
	0x3c, 0x33, 0xb6, 0x63, 0x25, 0x95, 0xbd, 0x3b, 0xad, 0xee, 0xef, 0x9e, 0xe3, 0x13, 0xdd, 0x81,
	0x7b, 0x01, 0xe1, 0xab, 0x4b, 0x41, 0xb8, 0xb8, 0x64, 0x99, 0xa0, 0x2c, 0xe5, 0x6e, 0x96, 0x33,
	0xc1, 0x1c, 0x28, 0xfe, 0xa7, 0x24, 0xbf, 0x3f, 0x8d, 0x18, 0x8b, 0x62, 0xe2, 0xa9, 0x3f, 0x97,
	0x32, 0xf4, 0x0a, 0x28, 0xa7, 0x99, 0x60, 0xb9, 0x9e, 0x7e, 0xb4, 0x80, 0xbb, 0x98, 0xf8, 0x71,
	0xfc, 0xe3, 0x9c, 0x26, 0x59, 0x4c, 0x3e, 0x10, 0xce, 0xfd, 0x88, 0x38, 0x07, 0xd0, 0xa3, 0xc1,
	0xc4, 0x9a, 0x5a, 0xb3, 0x3e, 0xee, 0xd1, 0xc0, 0x71, 0xa0, 0x9f, 0xfa, 0x09, 0x99, 0xf4, 0xa6,
	0xd6, 0x6c, 0x84, 0x95, 0x7e, 0x72, 0x04, 0xe3, 0x4d, 0xf4, 0x2c, 0x95, 0x89, 0x33, 0x82, 0xfd,
	0x8b, 0xd3, 0xf7, 0x9f, 0xcf, 0xc6, 0x16, 0x9a, 0xc3, 0x20, 0x09, 0xe5, 0xd2, 0xcf, 0x9d, 0x63,
	0x57, 0xc7, 0x70, 0xcb, 0x18, 0xae, 0xb1, 0xf9, 0xa4, 0x83, 0x4f, 0x7e, 0x7e, 0x9c, 0x5a, 0xb3,
	0x21, 0x36, 0xf3, 0xe8, 0x19, 0x0c, 0x42, 0x4d, 0x1e, 0x6d, 0x91, 0xef, 0x28, 0x89, 0x83, 0x0d,
	0x6e, 0x6f, 0x36, 0xc2, 0x66, 0x1a, 0xcd, 0xc1, 0xd6, 0x6a, 0xd9, 0x06, 0xfe, 0x2a, 0x0c, 0xff,
	0xc7, 0xe5, 0x38, 0x7a, 0x0a, 0x03, 0xa2, 0x1d, 0x0f, 0xb7, 0xc0, 0xe2, 0xbb, 0x1a, 0x41, 0xf7,
	0xb1, 0x19, 0x46, 0xcf, 0xc1, 0xd6, 0x8a, 0xb7, 0x70, 0xca, 0xef, 0x0e, 0x2e, 0xa7, 0xd1, 0x02,
	0x86, 0x46, 0x86, 0x2d, 0xe4, 0xef, 0x82, 0xbc, 0x8d, 0xab, 0xf1, 0xda, 0x53, 0xb6, 0x90, 0x7f,
	0x0a, 0xf2, 0x56, 0xe9, 0x29, 0x6b, 0x4f, 0xd9, 0xe6, 0xf9, 0xb7, 0x20, 0x6d, 0x5c, 0x8d, 0xa3,
	0x97, 0x60, 0x93, 0x2b, 0xdd, 0xcf, 0xc3, 0x9d, 0xe4, 0x85, 0x1f, 0xcb, 0xe6, 0xaf, 0xb9, 0x87,
	0x4b, 0x04, 0xbd, 0x82, 0xa1, 0x91, 0xbc, 0x0b, 0xae, 0xba, 0x72, 0x70, 0xc5, 0xa0, 0xd7, 0x30,
	0x2a, 0x75, 0xd8, 0x65, 0x81, 0xaa, 0x6c, 0x8c, 0x6b, 0x68, 0x23, 0x81, 0xec, 0xb2, 0x40, 0x35,
	0xd7, 0xaf, 0x12, 0xc8, 0x8d, 0x04, 0xb2, 0x53, 0x02, 0x55, 0xe0, 0x00, 0xd7, 0x10, 0xfa, 0x0a,
	0x03, 0x7e, 0xd3, 0x31, 0x9c, 0x93, 0xfc, 0x8a, 0xae, 0x9a, 0xf5, 0xfd, 0x77, 0x72, 0xec, 0xd6,
	0x77, 0xec, 0xee, 0x38, 0x51, 0x6c, 0x16, 0xa2, 0x2f, 0x60, 0x6b, 0x45, 0xda, 0x77, 0xab, 0x6e,
	0x0f, 0x4e, 0x0e, 0x6f, 0xda, 0x5d, 0x7c, 0x09, 0x2e, 0xd7, 0xa1, 0x05, 0xd8, 0x89, 0xd0, 0xa9,
	0x1f, 0xec, 0x38, 0x61, 0xb1, 0x66, 0xcd, 0x4b, 0xec, 0xe1, 0x72, 0x1e, 0xbd, 0x80, 0xa1, 0x91,
	0x41, 0x2b, 0xab, 0x42, 0x59, 0xb8, 0x02, 0xd0, 0x29, 0xd8, 0xe4, 0x5a, 0xfb, 0x3e, 0xde, 0x2e,
	0xfb, 0x5a, 0x90, 0x94, 0x53, 0x96, 0x62, 0x3f, 0x6d, 0xbc, 0x20, 0xc5, 0x4b, 0x50, 0x72, 0xe8,
	0x2d, 0x0c, 0x8d, 0x5c, 0x76, 0xde, 0x61, 0x1e, 0x85, 0x0a, 0x7c, 0x83, 0xbe, 0xcd, 0x23, 0x2a,
	0xd6, 0x72, 0xe9, 0xae, 0x58, 0xe2, 0x7d, 0x5f, 0xcb, 0x24, 0xd3, 0x2f, 0x69, 0x4e, 0xc2, 0x98,
	0xac, 0x84, 0x47, 0x53, 0x41, 0xf2, 0xd4, 0x8f, 0xbd, 0x88, 0xc5, 0x7e, 0x1a, 0x79, 0x75, 0xab,
	0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x23, 0x1f, 0xba, 0xd1, 0x9f, 0x05, 0x00, 0x00,
}
