// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: desc_test_options.proto

package testprotos

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ReallySimpleEnum int32

const (
	ReallySimpleEnum_VALUE ReallySimpleEnum = 1
)

var ReallySimpleEnum_name = map[int32]string{
	1: "VALUE",
}
var ReallySimpleEnum_value = map[string]int32{
	"VALUE": 1,
}

func (x ReallySimpleEnum) Enum() *ReallySimpleEnum {
	p := new(ReallySimpleEnum)
	*p = x
	return p
}
func (x ReallySimpleEnum) String() string {
	return proto.EnumName(ReallySimpleEnum_name, int32(x))
}
func (x *ReallySimpleEnum) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReallySimpleEnum_value, data, "ReallySimpleEnum")
	if err != nil {
		return err
	}
	*x = ReallySimpleEnum(value)
	return nil
}
func (ReallySimpleEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorDescTestOptions, []int{0}
}

type ReallySimpleMessage struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReallySimpleMessage) Reset()         { *m = ReallySimpleMessage{} }
func (m *ReallySimpleMessage) String() string { return proto.CompactTextString(m) }
func (*ReallySimpleMessage) ProtoMessage()    {}
func (*ReallySimpleMessage) Descriptor() ([]byte, []int) {
	return fileDescriptorDescTestOptions, []int{0}
}

func (m *ReallySimpleMessage) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ReallySimpleMessage) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

var E_Mfubar = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         10101,
	Name:          "testprotos.mfubar",
	Tag:           "varint,10101,opt,name=mfubar",
	Filename:      "desc_test_options.proto",
}

var E_Ffubar = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.FieldOptions)(nil),
	ExtensionType: ([]string)(nil),
	Field:         10101,
	Name:          "testprotos.ffubar",
	Tag:           "bytes,10101,rep,name=ffubar",
	Filename:      "desc_test_options.proto",
}

var E_Ffubarb = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.FieldOptions)(nil),
	ExtensionType: ([]byte)(nil),
	Field:         10102,
	Name:          "testprotos.ffubarb",
	Tag:           "bytes,10102,opt,name=ffubarb",
	Filename:      "desc_test_options.proto",
}

var E_Efubar = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         10101,
	Name:          "testprotos.efubar",
	Tag:           "varint,10101,opt,name=efubar",
	Filename:      "desc_test_options.proto",
}

var E_Efubars = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         10102,
	Name:          "testprotos.efubars",
	Tag:           "zigzag32,10102,opt,name=efubars",
	Filename:      "desc_test_options.proto",
}

var E_Efubarsf = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         10103,
	Name:          "testprotos.efubarsf",
	Tag:           "fixed32,10103,opt,name=efubarsf",
	Filename:      "desc_test_options.proto",
}

var E_Efubaru = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumOptions)(nil),
	ExtensionType: (*uint32)(nil),
	Field:         10104,
	Name:          "testprotos.efubaru",
	Tag:           "varint,10104,opt,name=efubaru",
	Filename:      "desc_test_options.proto",
}

var E_Efubaruf = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumOptions)(nil),
	ExtensionType: (*uint32)(nil),
	Field:         10105,
	Name:          "testprotos.efubaruf",
	Tag:           "fixed32,10105,opt,name=efubaruf",
	Filename:      "desc_test_options.proto",
}

var E_Evfubar = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumValueOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         10101,
	Name:          "testprotos.evfubar",
	Tag:           "varint,10101,opt,name=evfubar",
	Filename:      "desc_test_options.proto",
}

var E_Evfubars = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumValueOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         10102,
	Name:          "testprotos.evfubars",
	Tag:           "zigzag64,10102,opt,name=evfubars",
	Filename:      "desc_test_options.proto",
}

var E_Evfubarsf = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumValueOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         10103,
	Name:          "testprotos.evfubarsf",
	Tag:           "fixed64,10103,opt,name=evfubarsf",
	Filename:      "desc_test_options.proto",
}

var E_Evfubaru = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumValueOptions)(nil),
	ExtensionType: (*uint64)(nil),
	Field:         10104,
	Name:          "testprotos.evfubaru",
	Tag:           "varint,10104,opt,name=evfubaru",
	Filename:      "desc_test_options.proto",
}

var E_Evfubaruf = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.EnumValueOptions)(nil),
	ExtensionType: (*uint64)(nil),
	Field:         10105,
	Name:          "testprotos.evfubaruf",
	Tag:           "fixed64,10105,opt,name=evfubaruf",
	Filename:      "desc_test_options.proto",
}

var E_Sfubar = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.ServiceOptions)(nil),
	ExtensionType: (*ReallySimpleMessage)(nil),
	Field:         10101,
	Name:          "testprotos.sfubar",
	Tag:           "bytes,10101,opt,name=sfubar",
	Filename:      "desc_test_options.proto",
}

var E_Sfubare = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.ServiceOptions)(nil),
	ExtensionType: (*ReallySimpleEnum)(nil),
	Field:         10102,
	Name:          "testprotos.sfubare",
	Tag:           "varint,10102,opt,name=sfubare,enum=testprotos.ReallySimpleEnum",
	Filename:      "desc_test_options.proto",
}

var E_Mtfubar = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.MethodOptions)(nil),
	ExtensionType: ([]float32)(nil),
	Field:         10101,
	Name:          "testprotos.mtfubar",
	Tag:           "fixed32,10101,rep,name=mtfubar",
	Filename:      "desc_test_options.proto",
}

var E_Mtfubard = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.MethodOptions)(nil),
	ExtensionType: (*float64)(nil),
	Field:         10102,
	Name:          "testprotos.mtfubard",
	Tag:           "fixed64,10102,opt,name=mtfubard",
	Filename:      "desc_test_options.proto",
}

var E_Exfubar = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.ExtensionRangeOptions)(nil),
	ExtensionType: ([]string)(nil),
	Field:         10101,
	Name:          "testprotos.exfubar",
	Tag:           "bytes,10101,rep,name=exfubar",
	Filename:      "desc_test_options.proto",
}

var E_Exfubarb = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.ExtensionRangeOptions)(nil),
	ExtensionType: ([]byte)(nil),
	Field:         10102,
	Name:          "testprotos.exfubarb",
	Tag:           "bytes,10102,opt,name=exfubarb",
	Filename:      "desc_test_options.proto",
}

func init() {
	proto.RegisterType((*ReallySimpleMessage)(nil), "testprotos.ReallySimpleMessage")
	proto.RegisterEnum("testprotos.ReallySimpleEnum", ReallySimpleEnum_name, ReallySimpleEnum_value)
	proto.RegisterExtension(E_Mfubar)
	proto.RegisterExtension(E_Ffubar)
	proto.RegisterExtension(E_Ffubarb)
	proto.RegisterExtension(E_Efubar)
	proto.RegisterExtension(E_Efubars)
	proto.RegisterExtension(E_Efubarsf)
	proto.RegisterExtension(E_Efubaru)
	proto.RegisterExtension(E_Efubaruf)
	proto.RegisterExtension(E_Evfubar)
	proto.RegisterExtension(E_Evfubars)
	proto.RegisterExtension(E_Evfubarsf)
	proto.RegisterExtension(E_Evfubaru)
	proto.RegisterExtension(E_Evfubaruf)
	proto.RegisterExtension(E_Sfubar)
	proto.RegisterExtension(E_Sfubare)
	proto.RegisterExtension(E_Mtfubar)
	proto.RegisterExtension(E_Mtfubard)
	proto.RegisterExtension(E_Exfubar)
	proto.RegisterExtension(E_Exfubarb)
}

func init() { proto.RegisterFile("desc_test_options.proto", fileDescriptorDescTestOptions) }

var fileDescriptorDescTestOptions = []byte{
	// 523 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdd, 0x6f, 0xd3, 0x30,
	0x14, 0xc5, 0x95, 0x6e, 0x6b, 0xda, 0x0b, 0x8c, 0x12, 0x1e, 0xa8, 0xd0, 0xc6, 0x0a, 0x0f, 0xa8,
	0xe2, 0x21, 0x91, 0x26, 0x31, 0x5a, 0x83, 0x10, 0x03, 0x8d, 0x27, 0x3e, 0x24, 0x4f, 0x4c, 0xc0,
	0xcb, 0x94, 0x36, 0x4e, 0x6a, 0x94, 0xc4, 0x51, 0x6c, 0x4f, 0xe3, 0x0f, 0xe7, 0xeb, 0x0d, 0xc5,
	0x76, 0x92, 0x46, 0xed, 0x94, 0xbc, 0x9d, 0x4d, 0xf7, 0x77, 0xcf, 0xc9, 0xa9, 0xae, 0xe1, 0x41,
	0x40, 0xf8, 0xf2, 0x52, 0x10, 0x2e, 0x2e, 0x59, 0x26, 0x28, 0x4b, 0xb9, 0x9b, 0xe5, 0x4c, 0x30,
	0x07, 0x8a, 0xff, 0x29, 0xc9, 0x1f, 0x4e, 0x22, 0xc6, 0xa2, 0x98, 0x78, 0xea, 0xcf, 0x85, 0x0c,
	0xbd, 0x02, 0xca, 0x69, 0x26, 0x58, 0xae, 0xa7, 0x9f, 0xcc, 0xe1, 0x3e, 0x26, 0x7e, 0x1c, 0xff,
	0x3c, 0xa7, 0x49, 0x16, 0x93, 0x8f, 0x84, 0x73, 0x3f, 0x22, 0xce, 0x3e, 0xf4, 0x68, 0x30, 0xb6,
	0x26, 0xd6, 0x74, 0x17, 0xf7, 0x68, 0xe0, 0x38, 0xb0, 0x9b, 0xfa, 0x09, 0x19, 0xf7, 0x26, 0xd6,
	0x74, 0x88, 0x95, 0x7e, 0x76, 0x08, 0xa3, 0x75, 0xf4, 0x2c, 0x95, 0x89, 0x33, 0x84, 0xbd, 0x8b,
	0xd3, 0x0f, 0x5f, 0xce, 0x46, 0x16, 0x9a, 0x41, 0x3f, 0x09, 0xe5, 0xc2, 0xcf, 0x9d, 0x23, 0x57,
	0xc7, 0x70, 0xcb, 0x18, 0xae, 0xb1, 0xf9, 0xac, 0x83, 0x8f, 0x7f, 0x7d, 0x9a, 0x58, 0xd3, 0x01,
	0x36, 0xf3, 0xe8, 0x04, 0xfa, 0xa1, 0x26, 0x0f, 0x37, 0xc8, 0xf7, 0x94, 0xc4, 0xc1, 0x1a, 0xb7,
	0x33, 0x1d, 0x62, 0x33, 0x8d, 0x66, 0x60, 0x6b, 0xb5, 0x68, 0x03, 0x7f, 0x17, 0x86, 0xb7, 0x71,
	0x39, 0x8e, 0x9e, 0x43, 0x9f, 0x68, 0xc7, 0x83, 0x0d, 0xb0, 0xf8, 0xae, 0x46, 0xd0, 0x3d, 0x6c,
	0x86, 0xd1, 0x0b, 0xb0, 0xb5, 0xe2, 0x2d, 0x9c, 0xf2, 0xbb, 0x87, 0xcb, 0x69, 0x34, 0x87, 0x81,
	0x91, 0x61, 0x0b, 0xf9, 0xa7, 0x20, 0xef, 0xe2, 0x6a, 0xbc, 0xf6, 0x94, 0x2d, 0xe4, 0xdf, 0x82,
	0xbc, 0x53, 0x7a, 0xca, 0xda, 0x53, 0xb6, 0x79, 0xfe, 0x2b, 0x48, 0x1b, 0x57, 0xe3, 0xe8, 0x15,
	0xd8, 0xe4, 0x4a, 0xf7, 0xf3, 0x78, 0x2b, 0x79, 0xe1, 0xc7, 0xb2, 0xf9, 0x6b, 0xee, 0xe0, 0x12,
	0x41, 0xaf, 0x61, 0x60, 0x24, 0xef, 0x82, 0xab, 0xae, 0x1c, 0x5c, 0x31, 0xe8, 0x0d, 0x0c, 0x4b,
	0x1d, 0x76, 0x59, 0xa0, 0x2a, 0x1b, 0xe1, 0x1a, 0x5a, 0x4b, 0x20, 0xbb, 0x2c, 0x50, 0xcd, 0xed,
	0x56, 0x09, 0xe4, 0x5a, 0x02, 0xd9, 0x29, 0x81, 0x2a, 0xb0, 0x8f, 0x6b, 0x08, 0x7d, 0x83, 0x3e,
	0xbf, 0xe9, 0x18, 0xce, 0x49, 0x7e, 0x45, 0x97, 0xcd, 0xfa, 0x6e, 0x1d, 0x1f, 0xb9, 0xf5, 0x1d,
	0xbb, 0x5b, 0x4e, 0x14, 0x9b, 0x85, 0xe8, 0x2b, 0xd8, 0x5a, 0x91, 0xf6, 0xdd, 0xaa, 0xdb, 0xfd,
	0xe3, 0x83, 0x9b, 0x76, 0x17, 0x5f, 0x82, 0xcb, 0x75, 0x68, 0x0e, 0x76, 0x22, 0x74, 0xea, 0x47,
	0x5b, 0x4e, 0x58, 0xac, 0x58, 0xf3, 0x12, 0x7b, 0xb8, 0x9c, 0x47, 0x2f, 0x61, 0x60, 0x64, 0xd0,
	0xca, 0xaa, 0x50, 0x16, 0xae, 0x00, 0x74, 0x0a, 0x36, 0xb9, 0xd6, 0xbe, 0x4f, 0x37, 0xcb, 0xbe,
	0x16, 0x24, 0xe5, 0x94, 0xa5, 0xd8, 0x4f, 0x1b, 0x2f, 0x48, 0xf1, 0x12, 0x94, 0x1c, 0x7a, 0x07,
	0x03, 0x23, 0x17, 0x9d, 0x77, 0x98, 0x47, 0xa1, 0x02, 0xdf, 0xce, 0xbe, 0x9f, 0x44, 0x54, 0xac,
	0xe4, 0xc2, 0x5d, 0xb2, 0xc4, 0xfb, 0xb1, 0x92, 0x49, 0xa6, 0x5f, 0xd2, 0x9c, 0x84, 0x31, 0x59,
	0x0a, 0x8f, 0xa6, 0x82, 0xe4, 0xa9, 0x1f, 0x7b, 0x11, 0x8b, 0x98, 0x57, 0x77, 0xfa, 0x3f, 0x00,
	0x00, 0xff, 0xff, 0x7d, 0x8d, 0x40, 0x3e, 0x9d, 0x05, 0x00, 0x00,
}
