// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nopkg/desc_test_nopkg_new.proto

/*
Package nopkg is a generated protocol buffer package.

It is generated from these files:
	nopkg/desc_test_nopkg_new.proto
	nopkg/desc_test_nopkg.proto

It has these top-level messages:
	TopLevel
*/
package nopkg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TopLevel struct {
	I                            *int32   `protobuf:"varint,1,opt,name=i" json:"i,omitempty"`
	J                            *int64   `protobuf:"varint,2,opt,name=j" json:"j,omitempty"`
	K                            *int32   `protobuf:"zigzag32,3,opt,name=k" json:"k,omitempty"`
	L                            *int64   `protobuf:"zigzag64,4,opt,name=l" json:"l,omitempty"`
	M                            *uint32  `protobuf:"varint,5,opt,name=m" json:"m,omitempty"`
	N                            *uint64  `protobuf:"varint,6,opt,name=n" json:"n,omitempty"`
	O                            *uint32  `protobuf:"fixed32,7,opt,name=o" json:"o,omitempty"`
	P                            *uint64  `protobuf:"fixed64,8,opt,name=p" json:"p,omitempty"`
	Q                            *int32   `protobuf:"fixed32,9,opt,name=q" json:"q,omitempty"`
	R                            *int64   `protobuf:"fixed64,10,opt,name=r" json:"r,omitempty"`
	S                            *float32 `protobuf:"fixed32,11,opt,name=s" json:"s,omitempty"`
	T                            *float64 `protobuf:"fixed64,12,opt,name=t" json:"t,omitempty"`
	U                            []byte   `protobuf:"bytes,13,opt,name=u" json:"u,omitempty"`
	V                            *string  `protobuf:"bytes,14,opt,name=v" json:"v,omitempty"`
	W                            *bool    `protobuf:"varint,15,opt,name=w" json:"w,omitempty"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
}

func (m *TopLevel) Reset()                    { *m = TopLevel{} }
func (m *TopLevel) String() string            { return proto.CompactTextString(m) }
func (*TopLevel) ProtoMessage()               {}
func (*TopLevel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

var extRange_TopLevel = []proto.ExtensionRange{
	{100, 1000},
}

func (*TopLevel) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_TopLevel
}

func (m *TopLevel) GetI() int32 {
	if m != nil && m.I != nil {
		return *m.I
	}
	return 0
}

func (m *TopLevel) GetJ() int64 {
	if m != nil && m.J != nil {
		return *m.J
	}
	return 0
}

func (m *TopLevel) GetK() int32 {
	if m != nil && m.K != nil {
		return *m.K
	}
	return 0
}

func (m *TopLevel) GetL() int64 {
	if m != nil && m.L != nil {
		return *m.L
	}
	return 0
}

func (m *TopLevel) GetM() uint32 {
	if m != nil && m.M != nil {
		return *m.M
	}
	return 0
}

func (m *TopLevel) GetN() uint64 {
	if m != nil && m.N != nil {
		return *m.N
	}
	return 0
}

func (m *TopLevel) GetO() uint32 {
	if m != nil && m.O != nil {
		return *m.O
	}
	return 0
}

func (m *TopLevel) GetP() uint64 {
	if m != nil && m.P != nil {
		return *m.P
	}
	return 0
}

func (m *TopLevel) GetQ() int32 {
	if m != nil && m.Q != nil {
		return *m.Q
	}
	return 0
}

func (m *TopLevel) GetR() int64 {
	if m != nil && m.R != nil {
		return *m.R
	}
	return 0
}

func (m *TopLevel) GetS() float32 {
	if m != nil && m.S != nil {
		return *m.S
	}
	return 0
}

func (m *TopLevel) GetT() float64 {
	if m != nil && m.T != nil {
		return *m.T
	}
	return 0
}

func (m *TopLevel) GetU() []byte {
	if m != nil {
		return m.U
	}
	return nil
}

func (m *TopLevel) GetV() string {
	if m != nil && m.V != nil {
		return *m.V
	}
	return ""
}

func (m *TopLevel) GetW() bool {
	if m != nil && m.W != nil {
		return *m.W
	}
	return false
}

func init() {
	proto.RegisterType((*TopLevel)(nil), "TopLevel")
}

func init() { proto.RegisterFile("nopkg/desc_test_nopkg_new.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x1c, 0xd0, 0xbf, 0x4e, 0xc3, 0x40,
	0x0c, 0xc7, 0x71, 0xfd, 0xfa, 0x37, 0x0d, 0x2d, 0x2d, 0x9d, 0xbc, 0x61, 0x31, 0x59, 0x0c, 0xcd,
	0x03, 0xb0, 0x21, 0xc4, 0xc4, 0x64, 0x31, 0xb1, 0x54, 0xa5, 0x3d, 0xd2, 0xb4, 0xc9, 0x5d, 0x9a,
	0x5c, 0xda, 0x07, 0x66, 0xe2, 0x2d, 0x90, 0xb3, 0x58, 0xfa, 0x48, 0xf6, 0xe0, 0x6f, 0xfa, 0xe8,
	0x43, 0x7d, 0xce, 0xb3, 0x83, 0x6b, 0xf7, 0xdb, 0xe8, 0xda, 0xb8, 0xed, 0xbd, 0xf5, 0xee, 0xb6,
	0xa9, 0x9b, 0x10, 0xc3, 0xd3, 0x2f, 0xd2, 0xe4, 0x33, 0xd4, 0x1f, 0xee, 0xea, 0xca, 0xf5, 0x3c,
	0x45, 0x41, 0x60, 0xc8, 0x58, 0x51, 0x98, 0x4e, 0x34, 0x60, 0xc8, 0x50, 0x71, 0x32, 0x9d, 0x69,
	0xc8, 0x90, 0x07, 0xc5, 0xd9, 0x54, 0xd2, 0x88, 0x21, 0x6b, 0x45, 0x7f, 0x57, 0xd1, 0x98, 0x21,
	0x0b, 0x45, 0x65, 0xf2, 0x34, 0x61, 0xc8, 0x48, 0xe1, 0x4d, 0x81, 0xa6, 0x0c, 0x99, 0x2a, 0x82,
	0xa9, 0xa6, 0x84, 0x21, 0x13, 0x45, 0x6d, 0xba, 0xd0, 0x8c, 0x21, 0x4b, 0xc5, 0xc5, 0xd4, 0x50,
	0xca, 0x90, 0x95, 0xa2, 0x31, 0xb5, 0x74, 0xc7, 0x90, 0x81, 0xa2, 0x35, 0x45, 0x9a, 0x33, 0x04,
	0x8a, 0x68, 0xea, 0x68, 0xc1, 0x90, 0xb9, 0xa2, 0x33, 0x5d, 0xe9, 0x9e, 0x21, 0x33, 0xc5, 0xd5,
	0x74, 0xa3, 0x25, 0x43, 0x12, 0xc5, 0xed, 0x79, 0x9c, 0x1c, 0x56, 0x7f, 0xd3, 0xd7, 0xf7, 0xaf,
	0xb7, 0xbc, 0x88, 0xc7, 0xee, 0x7b, 0xb3, 0x0f, 0x55, 0x76, 0x3a, 0x76, 0x55, 0x9d, 0xf5, 0xff,
	0x37, 0xee, 0xa7, 0x74, 0xfb, 0x98, 0x15, 0x3e, 0xba, 0xc6, 0xef, 0xca, 0x2c, 0x0f, 0xe5, 0xce,
	0xe7, 0x99, 0xb5, 0xea, 0x17, 0xda, 0xac, 0x2f, 0xf6, 0xd2, 0xcf, 0xff, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x7e, 0x8e, 0x68, 0xd4, 0x4f, 0x01, 0x00, 0x00,
}
